# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lX9-trAhOWpLJqoeMsHtaocEfvYv8KmX
"""

# Define variables for two numbers and the operation
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operation = input("Enter the operation (+, -, *, /): ")

# Use conditionals to perform the operation
if operation == "+":
    result = num1 + num2
elif operation == "-":
    result = num1 - num2
elif operation == "*":
    result = num1 * num2
elif operation == "/":
    if num2 != 0:  # Avoid division by zero
        result = num1 / num2
    else:
        result = "Error: Division by zero is undefined."
else:
    result = "Invalid operation"

# Print the result
print(f"The result is: {result}")

# Function to convert Celsius to Fahrenheit
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

# Function to convert Fahrenheit to Celsius
def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

# Get input from the user
conversion_direction = input("Enter 'C' to convert Celsius to Fahrenheit or 'F' to convert Fahrenheit to Celsius: ").upper()

# Perform the conversion based on user's choice
if conversion_direction == "C":
    celsius = float(input("Enter the temperature in Celsius: "))
    fahrenheit = celsius_to_fahrenheit(celsius)
    print(f"{celsius}°C is equal to {fahrenheit}°F")

elif conversion_direction == "F":
    fahrenheit = float(input("Enter the temperature in Fahrenheit: "))
    celsius = fahrenheit_to_celsius(fahrenheit)
    print(f"{fahrenheit}°F is equal to {celsius}°C")

else:
    print("Invalid input. Please enter 'C' or 'F'.")

# Get input from the user
number = int(input("Enter a number: "))

# Use conditionals to check if the number is odd or even
if number % 2 == 0:
    print(f"{number} is even.")
else:
    print(f"{number} is odd.")

